### ISSUE TITLE
Rename "NtnuBlackboardScraper" to something more "abstract" as the bot is not NTNU specific

### ISSUE THREAD

**Issue by ANicholasson** [PersonligFrelser/bb-discord-announcer#17]

**Comment by libanbn** [comment]
The class does not only work for NTNU, that is true. The issue is that there are multiple versions of Blackboard with different web UIs and we don't know of any other except the one NTNU uses. As far as I know, NTNU is the only university using this seemingly obsolete version of Blackboard in Norway. 

Right now it's best to leave the name as it is because we only know that it works with NTNU's integration. This may change if we get more information on other integrations of Blackboard.
