### ISSUE TITLE
Is this still up?

### ISSUE THREAD

**Issue by Iamdeadlyz** [PersonligFrelser/bb-discord-announcer#9]
Heya,

Is this still up? A readme.md and other documentation in setting this up would be great. This looks super interesting and it would be really helpful for students like me who use BB.

Thanks a lot! ☺

**Comment by libanbn** [comment]
Hi Ian,

There has been few issues integrating the bot with BlackBoard mostly due to our school using an [older BB version](https://innsida.ntnu.no/c/wiki/get_page_attachment?p_l_id=22780&nodeId=24647&title=Blackboard+-+Bruk+av+sandkasse&fileName=1_1_finne_frem.jpg) from 2017. The case could be different with your school. The bot does work, but needs to be optimized, and in your situation, you may need to change the way messages are extracted from your schools BB. 

_As of now the project is discontinued_. If you want to further develop this project, I can release a README with all info you'd need (hopefully) during next week. Also, I have a friend that can update the bot and make implementation and development easier.

@Mairesu 

Thanks for showing interest 😎

**Comment by Iamdeadlyz** [comment]
Hey man,

That would be pretty great! I'm looking forward to the documentation and/or updates to the bot.

Thank you so much in advance! Stay safe and healthy~ 😊

**Comment by ANicholasson** [comment]
Sorry for the delay, we were in the midst of our bachelor project/thesis. We just picked up the project recently, and hopefully, we can create a version 1.0 before losing our access to Blackboard. You are welcome to join the development of the bot. We have a discord server (see link in README.md) available if you want to chat or have any questions regarding, development, setup, new features etc.
